id: P004521
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21596
  title: ཉམས་ཡིག་བརྒྱ་རྩ།
  author: ''
  volumes:
    0a0d2deaab644a08923e1a01f734c5d3:
      image_group_id: I1KG21691
      title: ''
      volume_number: 1
      total_pages: 238
