id: P004521
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:29:20.917540
source_metadata:
  id: bdr:W1KG21596
  title: ཉམས་ཡིག་བརྒྱ་རྩ།
  author: ''
  volumes:
    0a0d2deaab644a08923e1a01f734c5d3:
      image_group_id: I1KG21691
      title: ''
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
