id: I0087E47A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:25:17+00:00'
last_modified: '2022-06-08T01:40:12.414955+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21596
  title: ཉམས་ཡིག་བརྒྱ་རྩ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3147':
      image_group_id: I1KG21691
      title: ''
      total_pages: 238
      order: 1
      base_file: 3147.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
